# Generated by Django 2.2.3 on 2020-11-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20200517_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=70)),
                ('customer_email', models.EmailField(default='', max_length=70)),
                ('customer_phone', models.CharField(default='', max_length=13)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
    ]
