# Generated by Django 2.2.3 on 2020-11-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20201121_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.FloatField(default=''),
        ),
    ]
