# Generated by Django 2.2.3 on 2020-11-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20201121_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderupdate',
            name='order_id',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
