# Generated by Django 2.2.3 on 2020-12-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20201121_1442'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
