# Generated by Django 2.2.3 on 2020-12-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlidesImaes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
