# Generated by Django 2.2.3 on 2020-12-06 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_slidesimaes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SlidesImaes',
            new_name='SlidesImgaes',
        ),
    ]
